# fly.toml file generated for unnamedhouseplantr on 2023-02-08T10:38:52-05:00

app = "unnamedhouseplantr"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
DATABASE_URL="mongodb+srv://eljerpenny:RecognizE@cluster0.125qhto.mongodb.net/houseplants?retryWrites=true&w=majority"
MONGO_DEV_URI="mongodb://localhost/houseplants"

PORT = "8080"
SECRET = "iHopeIAmDoingThisRight"

API_URL_ALL = "https://house-plants2.p.rapidapi.com/all"
API_URL_CAT = "https://house-plants2.p.rapidapi.com/categories"

API_KEY = "fa772b2ccfmsha501e58960b67eap1babc2jsn2c0a909f7b3c"
API_HOST = "house-plants2.p.rapidapi.com"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
